# Name of the instance for failure messages
instance_name: LocalCrag

# Database configuration
db:
  host: your-database-host
  port: 5432
  user: backup
  password: backup-user-password
  name: localcrag

# MinIO configuration
minio:
  host: https://your-minio-host
  user: localcrag
  password: your-minio-secret
  bucket: localcrag

# Number and location of backups
backup:
  dir: ./backups
  keep: 5  # Number of backups to keep (-1 to keep all)

# SMTP config for failure emails
smtp:
  host: ''
  port: ''
  user: ''
  password: ''
  sender: ''
  receiver: ''

sftp:
  host: ftp.localcrag.cloud
  user: ftp_user
  password: ftp_password
  dir: /localcrag-backups

storage:
  type: local  # Options: local, sftp